language: python
sudo: true
python:
  - "3.6"

install:
  - cd data/
  - tar xf small_classification.tar.xz
  - cd ..
  - # install linux packages
  - sudo apt-get update
    # https://github.com/automl/auto-sklearn/issues/314
  - sudo apt-get remove swig
  - sudo apt-get install swig3.0
  - sudo ln -s /usr/bin/swig3.0 /usr/bin/swig
  - curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip install > /dev/null
  - pip install -r requirements.txt > /dev/null

script:
  - python3 -m unittest
