language: python
sudo: true
python:
  - "3.6"

install:
  - sudo apt-get remove swig
  - sudo apt-get install swig3.0
  - curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip install > /dev/null
  - pip install -r requirements.txt > /dev/null

script:
  - python3 -m unittest
